export const simpleDataType = {
  boolean: "BOOLEAN",
  true: "TRUE",
  false: "FALSE",
  text: "TEXT",
  real: "REAL",
  smallInt: "SMALLINT",
  int: "INTEGER",
  bigInt: "BIGINT",
  serial: "SERIAL",
  bigSerial: "BIGSERIAL",
  smallSerial: "SMALLSERIAL",
  double: "DOUBLE PRECISION",
  float: "FLOAT",
  float8: "FLOAT8",
  date: "DATE",
  timestamp: "TIMESTAMP",
  timestamptz: "TIMESTAMPTZ",
  time: "TIME",
  json: "JSON",
  jsonb: "JSONB",
  uuid: "UUID",
  null: "NULL",
  hstore: "HSTORE",
  bytea: "BYTEA",
  inet: "INET",
  cidr: "CIDR",
  // Need to Check
  // macaddr: 'MACADDR',
  // macaddr8: 'MACADDR8',
  // point: 'POINT',
  // line: 'LINE',
  // lseg: 'LINE SEGMENT',
  // lineSegment: 'LINE SEGMENT',
  // box: 'BOX',
  // path: 'PATH',
  // polygon: 'POLYGON',
  // circle: 'CIRCLE',
  // int4Range: 'INT4RANGE',
  // int8Range: 'INT8RANGE',
  // numRange: 'NUMRANGE',
  // tsRange: 'TSRANGE',
  // tstzRange: 'TSTZRANGE',
  // dateRange: 'DATERANGE',
} as const;
